// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/api/auth/callback.get').default>>>>
    }
    '/api/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/api/auth/google.get').default>>>>
    }
    '/api/boxes': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/api/boxes.post').default>>>>
    }
    '/api/save-names': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/api/save-names.post').default>>>>
    }
    '/ads.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/routes/ads.txt').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../app/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}