
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AboutSideMenu: typeof import("../app/components/AboutSideMenu.vue")['default']
export const AboutUs: typeof import("../app/components/AboutUs.vue")['default']
export const Activities: typeof import("../app/components/Activities.vue")['default']
export const Adsbygoogle: typeof import("../app/components/Adsbygoogle.vue")['default']
export const AnimoRunList: typeof import("../app/components/AnimoRunList.vue")['default']
export const AnimoRunRegistration: typeof import("../app/components/AnimoRunRegistration.vue")['default']
export const Banner: typeof import("../app/components/Banner.vue")['default']
export const BlogPosting: typeof import("../app/components/BlogPosting.vue")['default']
export const BorrowOfficesKey: typeof import("../app/components/BorrowOfficesKey/index.vue")['default']
export const Breadcrumb: typeof import("../app/components/Breadcrumb.vue")['default']
export const CMSForm: typeof import("../app/components/CMS/Form.vue")['default']
export const CMSList: typeof import("../app/components/CMS/List.vue")['default']
export const CampusPass: typeof import("../app/components/CampusPass/index.vue")['default']
export const CampusPassMenuBar: typeof import("../app/components/CampusPassMenuBar.vue")['default']
export const ChancellorOffice: typeof import("../app/components/ChancellorOffice/index.vue")['default']
export const ChancelorsUpdate: typeof import("../app/components/ChancelorsUpdate.vue")['default']
export const ComingSoon: typeof import("../app/components/ComingSoon.vue")['default']
export const CommissionOnElectionAddCandidates: typeof import("../app/components/CommissionOnElection/AddCandidates.vue")['default']
export const CommissionOnElectionListEnrolledStudents: typeof import("../app/components/CommissionOnElection/ListEnrolledStudents.vue")['default']
export const CommissionOnElectionStudentElectionResults: typeof import("../app/components/CommissionOnElection/StudentElectionResults.vue")['default']
export const CommissionOnElectionStudentElectionVoting: typeof import("../app/components/CommissionOnElection/StudentElectionVoting.vue")['default']
export const CommissionOnElectionBEUAddCandidates: typeof import("../app/components/CommissionOnElectionBEU/AddCandidates.vue")['default']
export const CommissionOnElectionBEUListEnrolledStudents: typeof import("../app/components/CommissionOnElectionBEU/ListEnrolledStudents.vue")['default']
export const CommissionOnElectionBEUStudentElectionResults: typeof import("../app/components/CommissionOnElectionBEU/StudentElectionResults.vue")['default']
export const CommissionOnElectionBEUStudentElectionVoting: typeof import("../app/components/CommissionOnElectionBEU/StudentElectionVoting.vue")['default']
export const Countdown: typeof import("../app/components/Countdown.vue")['default']
export const DashboardFooter: typeof import("../app/components/DashboardFooter.vue")['default']
export const DataProcessDPO: typeof import("../app/components/DataProcessDPO/index.vue")['default']
export const DocumentRequestForm: typeof import("../app/components/DocumentRequestForm.vue")['default']
export const DocumentReviewSystemForm: typeof import("../app/components/DocumentReviewSystem/Form.vue")['default']
export const DocumentReviewSystemList: typeof import("../app/components/DocumentReviewSystem/List.vue")['default']
export const DynamicSideMenu: typeof import("../app/components/DynamicSideMenu/index.vue")['default']
export const EnrollmentMenuBar: typeof import("../app/components/EnrollmentMenuBar.vue")['default']
export const FAQs: typeof import("../app/components/FAQs/index.vue")['default']
export const Footer: typeof import("../app/components/Footer.vue")['default']
export const FooterInvestiture: typeof import("../app/components/FooterInvestiture.vue")['default']
export const GSOFacilitiesReservationForm: typeof import("../app/components/GSO/FacilitiesReservationForm.vue")['default']
export const GSOFacilitiesReservationList: typeof import("../app/components/GSO/FacilitiesReservationList.vue")['default']
export const GSOFacilitySelector: typeof import("../app/components/GSO/FacilitySelector.vue")['default']
export const GSOVehicleReservationForm: typeof import("../app/components/GSO/VehicleReservationForm.vue")['default']
export const GSOVehicleReservationList: typeof import("../app/components/GSO/VehicleReservationList.vue")['default']
export const GSOVehicleSelector: typeof import("../app/components/GSO/VehicleSelector.vue")['default']
export const GoogleAdsense: typeof import("../app/components/GoogleAdsense/index.vue")['default']
export const GoogleDriveEmbed: typeof import("../app/components/GoogleDriveEmbed/index.vue")['default']
export const Header: typeof import("../app/components/Header.vue")['default']
export const HeroCarousel: typeof import("../app/components/HeroCarousel.vue")['default']
export const HeroLanding: typeof import("../app/components/HeroLanding.vue")['default']
export const HumanResourceEmployedAdmins: typeof import("../app/components/HumanResource/EmployedAdmins.vue")['default']
export const HumanResource: typeof import("../app/components/HumanResource/index.vue")['default']
export const HumanResourceRaffle: typeof import("../app/components/HumanResource/raffle.vue")['default']
export const ITFeedback: typeof import("../app/components/ITFeedback/index.vue")['default']
export const InvestitureDonationBox: typeof import("../app/components/InvestitureDonationBox.vue")['default']
export const JurisDoctorAdmin: typeof import("../app/components/JurisDoctor/Admin.vue")['default']
export const JurisDoctorAdmission: typeof import("../app/components/JurisDoctor/Admission.vue")['default']
export const LibraryElectronicResources: typeof import("../app/components/Library/ElectronicResources.vue")['default']
export const LibraryBooks: typeof import("../app/components/Library/books/index.vue")['default']
export const LibraryReserved: typeof import("../app/components/Library/reserved/index.vue")['default']
export const LibrarySchedules: typeof import("../app/components/Library/schedules/index.vue")['default']
export const LibrarySchedulesUseSchedules: typeof import("../app/components/Library/schedules/useSchedules")['default']
export const LibrarySchedulesWorking: typeof import("../app/components/Library/schedules/working.vue")['default']
export const LibraryMenuBar: typeof import("../app/components/LibraryMenuBar.vue")['default']
export const LibraryMenuBarBorrower: typeof import("../app/components/LibraryMenuBarBorrower.vue")['default']
export const Logout: typeof import("../app/components/Logout.vue")['default']
export const McoMenuBar: typeof import("../app/components/McoMenuBar.vue")['default']
export const MoodTicket: typeof import("../app/components/MoodTicket.vue")['default']
export const NPCC: typeof import("../app/components/NPCC/index.vue")['default']
export const NetworkLogo: typeof import("../app/components/NetworkLogo.vue")['default']
export const NewsAndUpdates: typeof import("../app/components/NewsAndUpdates.vue")['default']
export const OERForm: typeof import("../app/components/OER/Form.vue")['default']
export const OERList: typeof import("../app/components/OER/List.vue")['default']
export const Pagination: typeof import("../app/components/Pagination.vue")['default']
export const Panaglambigit: typeof import("../app/components/Panaglambigit.vue")['default']
export const PopularCourses: typeof import("../app/components/PopularCourses.vue")['default']
export const ProcurementFooter: typeof import("../app/components/ProcurementFooter.vue")['default']
export const ProcurementMenuBar: typeof import("../app/components/ProcurementMenuBar.vue")['default']
export const RegistrarChatCommunicationModal: typeof import("../app/components/Registrar/ChatCommunicationModal.vue")['default']
export const RegistrarDeleteConfirmationModal: typeof import("../app/components/Registrar/DeleteConfirmationModal.vue")['default']
export const RegistrarDocumentPreparationModal: typeof import("../app/components/Registrar/DocumentPreparationModal.vue")['default']
export const RegistrarFilters: typeof import("../app/components/Registrar/Filters.vue")['default']
export const RegistrarList: typeof import("../app/components/Registrar/List.vue")['default']
export const RegistrarPagination: typeof import("../app/components/Registrar/Pagination.vue")['default']
export const RegistrarPaymentDetailsModal: typeof import("../app/components/Registrar/PaymentDetailsModal.vue")['default']
export const RegistrarPersonalInfoModal: typeof import("../app/components/Registrar/PersonalInfoModal.vue")['default']
export const RegistrarReleasingDocumentsModal: typeof import("../app/components/Registrar/ReleasingDocumentsModal.vue")['default']
export const RegistrarShowImageModal: typeof import("../app/components/Registrar/ShowImageModal.vue")['default']
export const RegistrarStatusCounters: typeof import("../app/components/Registrar/StatusCounters.vue")['default']
export const RegistrarStatusLogsModal: typeof import("../app/components/Registrar/StatusLogsModal.vue")['default']
export const RegistrarTransactionClosedModal: typeof import("../app/components/Registrar/TransactionClosedModal.vue")['default']
export const RegistrarVerifyErrorMessageToaster: typeof import("../app/components/Registrar/VerifyErrorMessageToaster.vue")['default']
export const RegistrarVerifySuccessMessageToaster: typeof import("../app/components/Registrar/VerifySuccessMessageToaster.vue")['default']
export const Registrar: typeof import("../app/components/Registrar/index.vue")['default']
export const RegistrarMenuBar: typeof import("../app/components/RegistrarMenuBar.vue")['default']
export const RegistrarPrivacyPolicy: typeof import("../app/components/RegistrarPrivacyPolicy.vue")['default']
export const SDG: typeof import("../app/components/SDG.vue")['default']
export const Shortcuts: typeof import("../app/components/Shortcuts.vue")['default']
export const Slider: typeof import("../app/components/Slider.vue")['default']
export const SliderAlt: typeof import("../app/components/SliderAlt.vue")['default']
export const SliderInvestiture: typeof import("../app/components/SliderInvestiture.vue")['default']
export const Slides: typeof import("../app/components/Slides.vue")['default']
export const StudentBlog: typeof import("../app/components/StudentBlog.vue")['default']
export const Students: typeof import("../app/components/Students.vue")['default']
export const SuperAdminDashboard: typeof import("../app/components/SuperAdminDashboard.vue")['default']
export const SuperAdminDashboardExternalLinks: typeof import("../app/components/SuperAdminDashboardExternalLinks.vue")['default']
export const SuperAdminDashboardLoading: typeof import("../app/components/SuperAdminDashboardLoading.vue")['default']
export const SuperAdminDashboardMenuList: typeof import("../app/components/SuperAdminDashboardMenuList.vue")['default']
export const SuperAdminDashboardNavigation: typeof import("../app/components/SuperAdminDashboardNavigation.vue")['default']
export const SuperAdminDashboardProfile: typeof import("../app/components/SuperAdminDashboardProfile.vue")['default']
export const SuperAdminDashboardRolePermissions: typeof import("../app/components/SuperAdminDashboardRolePermissions.vue")['default']
export const SuperAdminDashboardWelcome: typeof import("../app/components/SuperAdminDashboardWelcome.vue")['default']
export const TUKIB: typeof import("../app/components/TUKIB.vue")['default']
export const Testimonials: typeof import("../app/components/Testimonials.vue")['default']
export const ThankYouNotifFromFormSubmit: typeof import("../app/components/ThankYouNotifFromFormSubmit.vue")['default']
export const TingogMagazine: typeof import("../app/components/TingogMagazine.vue")['default']
export const ToggleDarkLightMode: typeof import("../app/components/ToggleDarkLightMode.vue")['default']
export const TotalAmount: typeof import("../app/components/TotalAmount.vue")['default']
export const TotalDonationNumberOnly: typeof import("../app/components/TotalDonationNumberOnly.vue")['default']
export const UniversityCalendar: typeof import("../app/components/UniversityCalendar.vue")['default']
export const UniversityDashboard: typeof import("../app/components/UniversityDashboard.vue")['default']
export const UniversityFeedbackWidget: typeof import("../app/components/UniversityFeedbackWidget.vue")['default']
export const UniversityLogin: typeof import("../app/components/UniversityLogin.vue")['default']
export const UpdatingPage: typeof import("../app/components/UpdatingPage.vue")['default']
export const Waves: typeof import("../app/components/Waves.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAboutSideMenu: LazyComponent<typeof import("../app/components/AboutSideMenu.vue")['default']>
export const LazyAboutUs: LazyComponent<typeof import("../app/components/AboutUs.vue")['default']>
export const LazyActivities: LazyComponent<typeof import("../app/components/Activities.vue")['default']>
export const LazyAdsbygoogle: LazyComponent<typeof import("../app/components/Adsbygoogle.vue")['default']>
export const LazyAnimoRunList: LazyComponent<typeof import("../app/components/AnimoRunList.vue")['default']>
export const LazyAnimoRunRegistration: LazyComponent<typeof import("../app/components/AnimoRunRegistration.vue")['default']>
export const LazyBanner: LazyComponent<typeof import("../app/components/Banner.vue")['default']>
export const LazyBlogPosting: LazyComponent<typeof import("../app/components/BlogPosting.vue")['default']>
export const LazyBorrowOfficesKey: LazyComponent<typeof import("../app/components/BorrowOfficesKey/index.vue")['default']>
export const LazyBreadcrumb: LazyComponent<typeof import("../app/components/Breadcrumb.vue")['default']>
export const LazyCMSForm: LazyComponent<typeof import("../app/components/CMS/Form.vue")['default']>
export const LazyCMSList: LazyComponent<typeof import("../app/components/CMS/List.vue")['default']>
export const LazyCampusPass: LazyComponent<typeof import("../app/components/CampusPass/index.vue")['default']>
export const LazyCampusPassMenuBar: LazyComponent<typeof import("../app/components/CampusPassMenuBar.vue")['default']>
export const LazyChancellorOffice: LazyComponent<typeof import("../app/components/ChancellorOffice/index.vue")['default']>
export const LazyChancelorsUpdate: LazyComponent<typeof import("../app/components/ChancelorsUpdate.vue")['default']>
export const LazyComingSoon: LazyComponent<typeof import("../app/components/ComingSoon.vue")['default']>
export const LazyCommissionOnElectionAddCandidates: LazyComponent<typeof import("../app/components/CommissionOnElection/AddCandidates.vue")['default']>
export const LazyCommissionOnElectionListEnrolledStudents: LazyComponent<typeof import("../app/components/CommissionOnElection/ListEnrolledStudents.vue")['default']>
export const LazyCommissionOnElectionStudentElectionResults: LazyComponent<typeof import("../app/components/CommissionOnElection/StudentElectionResults.vue")['default']>
export const LazyCommissionOnElectionStudentElectionVoting: LazyComponent<typeof import("../app/components/CommissionOnElection/StudentElectionVoting.vue")['default']>
export const LazyCommissionOnElectionBEUAddCandidates: LazyComponent<typeof import("../app/components/CommissionOnElectionBEU/AddCandidates.vue")['default']>
export const LazyCommissionOnElectionBEUListEnrolledStudents: LazyComponent<typeof import("../app/components/CommissionOnElectionBEU/ListEnrolledStudents.vue")['default']>
export const LazyCommissionOnElectionBEUStudentElectionResults: LazyComponent<typeof import("../app/components/CommissionOnElectionBEU/StudentElectionResults.vue")['default']>
export const LazyCommissionOnElectionBEUStudentElectionVoting: LazyComponent<typeof import("../app/components/CommissionOnElectionBEU/StudentElectionVoting.vue")['default']>
export const LazyCountdown: LazyComponent<typeof import("../app/components/Countdown.vue")['default']>
export const LazyDashboardFooter: LazyComponent<typeof import("../app/components/DashboardFooter.vue")['default']>
export const LazyDataProcessDPO: LazyComponent<typeof import("../app/components/DataProcessDPO/index.vue")['default']>
export const LazyDocumentRequestForm: LazyComponent<typeof import("../app/components/DocumentRequestForm.vue")['default']>
export const LazyDocumentReviewSystemForm: LazyComponent<typeof import("../app/components/DocumentReviewSystem/Form.vue")['default']>
export const LazyDocumentReviewSystemList: LazyComponent<typeof import("../app/components/DocumentReviewSystem/List.vue")['default']>
export const LazyDynamicSideMenu: LazyComponent<typeof import("../app/components/DynamicSideMenu/index.vue")['default']>
export const LazyEnrollmentMenuBar: LazyComponent<typeof import("../app/components/EnrollmentMenuBar.vue")['default']>
export const LazyFAQs: LazyComponent<typeof import("../app/components/FAQs/index.vue")['default']>
export const LazyFooter: LazyComponent<typeof import("../app/components/Footer.vue")['default']>
export const LazyFooterInvestiture: LazyComponent<typeof import("../app/components/FooterInvestiture.vue")['default']>
export const LazyGSOFacilitiesReservationForm: LazyComponent<typeof import("../app/components/GSO/FacilitiesReservationForm.vue")['default']>
export const LazyGSOFacilitiesReservationList: LazyComponent<typeof import("../app/components/GSO/FacilitiesReservationList.vue")['default']>
export const LazyGSOFacilitySelector: LazyComponent<typeof import("../app/components/GSO/FacilitySelector.vue")['default']>
export const LazyGSOVehicleReservationForm: LazyComponent<typeof import("../app/components/GSO/VehicleReservationForm.vue")['default']>
export const LazyGSOVehicleReservationList: LazyComponent<typeof import("../app/components/GSO/VehicleReservationList.vue")['default']>
export const LazyGSOVehicleSelector: LazyComponent<typeof import("../app/components/GSO/VehicleSelector.vue")['default']>
export const LazyGoogleAdsense: LazyComponent<typeof import("../app/components/GoogleAdsense/index.vue")['default']>
export const LazyGoogleDriveEmbed: LazyComponent<typeof import("../app/components/GoogleDriveEmbed/index.vue")['default']>
export const LazyHeader: LazyComponent<typeof import("../app/components/Header.vue")['default']>
export const LazyHeroCarousel: LazyComponent<typeof import("../app/components/HeroCarousel.vue")['default']>
export const LazyHeroLanding: LazyComponent<typeof import("../app/components/HeroLanding.vue")['default']>
export const LazyHumanResourceEmployedAdmins: LazyComponent<typeof import("../app/components/HumanResource/EmployedAdmins.vue")['default']>
export const LazyHumanResource: LazyComponent<typeof import("../app/components/HumanResource/index.vue")['default']>
export const LazyHumanResourceRaffle: LazyComponent<typeof import("../app/components/HumanResource/raffle.vue")['default']>
export const LazyITFeedback: LazyComponent<typeof import("../app/components/ITFeedback/index.vue")['default']>
export const LazyInvestitureDonationBox: LazyComponent<typeof import("../app/components/InvestitureDonationBox.vue")['default']>
export const LazyJurisDoctorAdmin: LazyComponent<typeof import("../app/components/JurisDoctor/Admin.vue")['default']>
export const LazyJurisDoctorAdmission: LazyComponent<typeof import("../app/components/JurisDoctor/Admission.vue")['default']>
export const LazyLibraryElectronicResources: LazyComponent<typeof import("../app/components/Library/ElectronicResources.vue")['default']>
export const LazyLibraryBooks: LazyComponent<typeof import("../app/components/Library/books/index.vue")['default']>
export const LazyLibraryReserved: LazyComponent<typeof import("../app/components/Library/reserved/index.vue")['default']>
export const LazyLibrarySchedules: LazyComponent<typeof import("../app/components/Library/schedules/index.vue")['default']>
export const LazyLibrarySchedulesUseSchedules: LazyComponent<typeof import("../app/components/Library/schedules/useSchedules")['default']>
export const LazyLibrarySchedulesWorking: LazyComponent<typeof import("../app/components/Library/schedules/working.vue")['default']>
export const LazyLibraryMenuBar: LazyComponent<typeof import("../app/components/LibraryMenuBar.vue")['default']>
export const LazyLibraryMenuBarBorrower: LazyComponent<typeof import("../app/components/LibraryMenuBarBorrower.vue")['default']>
export const LazyLogout: LazyComponent<typeof import("../app/components/Logout.vue")['default']>
export const LazyMcoMenuBar: LazyComponent<typeof import("../app/components/McoMenuBar.vue")['default']>
export const LazyMoodTicket: LazyComponent<typeof import("../app/components/MoodTicket.vue")['default']>
export const LazyNPCC: LazyComponent<typeof import("../app/components/NPCC/index.vue")['default']>
export const LazyNetworkLogo: LazyComponent<typeof import("../app/components/NetworkLogo.vue")['default']>
export const LazyNewsAndUpdates: LazyComponent<typeof import("../app/components/NewsAndUpdates.vue")['default']>
export const LazyOERForm: LazyComponent<typeof import("../app/components/OER/Form.vue")['default']>
export const LazyOERList: LazyComponent<typeof import("../app/components/OER/List.vue")['default']>
export const LazyPagination: LazyComponent<typeof import("../app/components/Pagination.vue")['default']>
export const LazyPanaglambigit: LazyComponent<typeof import("../app/components/Panaglambigit.vue")['default']>
export const LazyPopularCourses: LazyComponent<typeof import("../app/components/PopularCourses.vue")['default']>
export const LazyProcurementFooter: LazyComponent<typeof import("../app/components/ProcurementFooter.vue")['default']>
export const LazyProcurementMenuBar: LazyComponent<typeof import("../app/components/ProcurementMenuBar.vue")['default']>
export const LazyRegistrarChatCommunicationModal: LazyComponent<typeof import("../app/components/Registrar/ChatCommunicationModal.vue")['default']>
export const LazyRegistrarDeleteConfirmationModal: LazyComponent<typeof import("../app/components/Registrar/DeleteConfirmationModal.vue")['default']>
export const LazyRegistrarDocumentPreparationModal: LazyComponent<typeof import("../app/components/Registrar/DocumentPreparationModal.vue")['default']>
export const LazyRegistrarFilters: LazyComponent<typeof import("../app/components/Registrar/Filters.vue")['default']>
export const LazyRegistrarList: LazyComponent<typeof import("../app/components/Registrar/List.vue")['default']>
export const LazyRegistrarPagination: LazyComponent<typeof import("../app/components/Registrar/Pagination.vue")['default']>
export const LazyRegistrarPaymentDetailsModal: LazyComponent<typeof import("../app/components/Registrar/PaymentDetailsModal.vue")['default']>
export const LazyRegistrarPersonalInfoModal: LazyComponent<typeof import("../app/components/Registrar/PersonalInfoModal.vue")['default']>
export const LazyRegistrarReleasingDocumentsModal: LazyComponent<typeof import("../app/components/Registrar/ReleasingDocumentsModal.vue")['default']>
export const LazyRegistrarShowImageModal: LazyComponent<typeof import("../app/components/Registrar/ShowImageModal.vue")['default']>
export const LazyRegistrarStatusCounters: LazyComponent<typeof import("../app/components/Registrar/StatusCounters.vue")['default']>
export const LazyRegistrarStatusLogsModal: LazyComponent<typeof import("../app/components/Registrar/StatusLogsModal.vue")['default']>
export const LazyRegistrarTransactionClosedModal: LazyComponent<typeof import("../app/components/Registrar/TransactionClosedModal.vue")['default']>
export const LazyRegistrarVerifyErrorMessageToaster: LazyComponent<typeof import("../app/components/Registrar/VerifyErrorMessageToaster.vue")['default']>
export const LazyRegistrarVerifySuccessMessageToaster: LazyComponent<typeof import("../app/components/Registrar/VerifySuccessMessageToaster.vue")['default']>
export const LazyRegistrar: LazyComponent<typeof import("../app/components/Registrar/index.vue")['default']>
export const LazyRegistrarMenuBar: LazyComponent<typeof import("../app/components/RegistrarMenuBar.vue")['default']>
export const LazyRegistrarPrivacyPolicy: LazyComponent<typeof import("../app/components/RegistrarPrivacyPolicy.vue")['default']>
export const LazySDG: LazyComponent<typeof import("../app/components/SDG.vue")['default']>
export const LazyShortcuts: LazyComponent<typeof import("../app/components/Shortcuts.vue")['default']>
export const LazySlider: LazyComponent<typeof import("../app/components/Slider.vue")['default']>
export const LazySliderAlt: LazyComponent<typeof import("../app/components/SliderAlt.vue")['default']>
export const LazySliderInvestiture: LazyComponent<typeof import("../app/components/SliderInvestiture.vue")['default']>
export const LazySlides: LazyComponent<typeof import("../app/components/Slides.vue")['default']>
export const LazyStudentBlog: LazyComponent<typeof import("../app/components/StudentBlog.vue")['default']>
export const LazyStudents: LazyComponent<typeof import("../app/components/Students.vue")['default']>
export const LazySuperAdminDashboard: LazyComponent<typeof import("../app/components/SuperAdminDashboard.vue")['default']>
export const LazySuperAdminDashboardExternalLinks: LazyComponent<typeof import("../app/components/SuperAdminDashboardExternalLinks.vue")['default']>
export const LazySuperAdminDashboardLoading: LazyComponent<typeof import("../app/components/SuperAdminDashboardLoading.vue")['default']>
export const LazySuperAdminDashboardMenuList: LazyComponent<typeof import("../app/components/SuperAdminDashboardMenuList.vue")['default']>
export const LazySuperAdminDashboardNavigation: LazyComponent<typeof import("../app/components/SuperAdminDashboardNavigation.vue")['default']>
export const LazySuperAdminDashboardProfile: LazyComponent<typeof import("../app/components/SuperAdminDashboardProfile.vue")['default']>
export const LazySuperAdminDashboardRolePermissions: LazyComponent<typeof import("../app/components/SuperAdminDashboardRolePermissions.vue")['default']>
export const LazySuperAdminDashboardWelcome: LazyComponent<typeof import("../app/components/SuperAdminDashboardWelcome.vue")['default']>
export const LazyTUKIB: LazyComponent<typeof import("../app/components/TUKIB.vue")['default']>
export const LazyTestimonials: LazyComponent<typeof import("../app/components/Testimonials.vue")['default']>
export const LazyThankYouNotifFromFormSubmit: LazyComponent<typeof import("../app/components/ThankYouNotifFromFormSubmit.vue")['default']>
export const LazyTingogMagazine: LazyComponent<typeof import("../app/components/TingogMagazine.vue")['default']>
export const LazyToggleDarkLightMode: LazyComponent<typeof import("../app/components/ToggleDarkLightMode.vue")['default']>
export const LazyTotalAmount: LazyComponent<typeof import("../app/components/TotalAmount.vue")['default']>
export const LazyTotalDonationNumberOnly: LazyComponent<typeof import("../app/components/TotalDonationNumberOnly.vue")['default']>
export const LazyUniversityCalendar: LazyComponent<typeof import("../app/components/UniversityCalendar.vue")['default']>
export const LazyUniversityDashboard: LazyComponent<typeof import("../app/components/UniversityDashboard.vue")['default']>
export const LazyUniversityFeedbackWidget: LazyComponent<typeof import("../app/components/UniversityFeedbackWidget.vue")['default']>
export const LazyUniversityLogin: LazyComponent<typeof import("../app/components/UniversityLogin.vue")['default']>
export const LazyUpdatingPage: LazyComponent<typeof import("../app/components/UpdatingPage.vue")['default']>
export const LazyWaves: LazyComponent<typeof import("../app/components/Waves.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
